-define(DBC_FOLDER,     "dbc").
-define(INDEX_FOLDER,   "dbc/index").
-define(FILE_EXTENTION, "dbc").
-define(METADATA_FILE,  "meta.json").
-define(INDEX_FILE,     "index.json").
-define(MSG_FILE,       "msg.json").
-define(IN_PROGRESS,    "In progress").
-define(DONE,           "Done").
-define(UNKNOWN,        "Unknown").
-define(MESSAGE_ID_PREFIX,  "BO_").